name: Python CI

on:
  [ push, pull_request ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        python: [ 2.7, 3.7 ]
        splunk-version:
          - "8.1"
          - "8.2"
          - "latest"
      fail-fast: false

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6b3083af2869dc3314a0257a42f4af696cc79ba3 # v2.3.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2.7.0

      - name: Run docker-compose
        run: SPLUNK_VERSION=${{matrix.splunk-version}} docker-compose up -d

      - name: Setup Python
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: ${{ matrix.python }}

      - name: Install tox
        run: pip install tox

      - name: Test Execution
        run: tox -e py
